# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-20 19:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20170720_1858'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disciplina',
            name='eh_eletiva',
        ),
    ]
