# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-20 19:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_disciplina_eh_eletiva'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disciplina',
            name='tipo_eletiva',
            field=models.CharField(choices=[('perfil', 'Perfil'), ('livre', 'Livre'), ('obrigatoria', 'Obrigatoria')], default='obrigatoria', max_length=10),
        ),
    ]
