# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-27 11:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20170726_0223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Curso'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='rank',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
    ]
