# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-20 18:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20170720_1824'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disciplinas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=5)),
                ('data_de_insercao', models.DateField()),
                ('eh_eletiva', models.BooleanField(default=False)),
                ('tipo_eletiva', models.CharField(choices=[('perfil', 'Perfil'), ('livre', 'Livre'), (None, 'Obrigatoria')], default=None, max_length=10)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Curso')),
            ],
        ),
    ]
