# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-25 18:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20170720_1904'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aluno',
            name='rank',
        ),
    ]
