# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-26 02:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_remove_aluno_data_nascimento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='curso',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.Curso'),
        ),
    ]
