# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-26 02:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20170726_0219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='rank',
            field=models.DecimalField(decimal_places=2, default=5, max_digits=3),
        ),
    ]
