# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-27 12:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_aluno_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='rank',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
    ]
