# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-31 02:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20170727_1224'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='foto',
            field=models.ImageField(default=0, upload_to=''),
            preserve_default=False,
        ),
    ]
